### ISSUE TITLE
Add workflow for making a PR based on user filing issues

### ISSUE THREAD

**Issue by cmungall** [hrshdhgd/onto-crawler#8]
We can copy what Charlie did here:

https://github.com/biopragmatics/bioregistry/blob/main/.github/workflows/new_prefix_pr.yml

This triggers:

https://github.com/biopragmatics/bioregistry/blob/main/src/bioregistry/gh/new_prefix.py

- user submits an issue using KCDL DSL
- gh action periodically runs ocrawl (analogous to new_prefix_pr.yml)
- ocrawl executes changes and modifies the src ontology file (analogous to new_prefix.py)
- make a PR (covered in the workflow above)

**Comment by hrshdhgd** [comment]
Also by [this workflow](https://github.com/hrshdhgd/mondo/blob/master/.github/workflows/new-pr.yml)
